namespace TranscriptHelper.Core.Models;

/// <summary>
/// Represents an auto-generated summary of a range of transcript entries.
/// Used for long meetings to reduce token usage in AI prompts via contextual summarization.
/// </summary>
public sealed record RollingSummary(
    /// <summary>When the summary was generated.</summary>
    DateTimeOffset Timestamp,
    
    /// <summary>How many transcript entries were included in this summary.</summary>
    int EntriesCount,
    
    /// <summary>The summarized content (generated by AI or marker-based extraction).</summary>
    string SummaryText,
    
    /// <summary>Key participants mentioned in this summary window.</summary>
    IReadOnlyList<string> KeyParticipants
);
